// Auth Action Types
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
// OTP
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// Ride Action Types
export const BOOK_RIDE_REQUEST = 'BOOK_RIDE_REQUEST';
export const BOOK_RIDE_SUCCESS = 'BOOK_RIDE_SUCCESS';
export const BOOK_RIDE_FAILURE = 'BOOK_RIDE_FAILURE';

export const CANCEL_RIDE = 'CANCEL_RIDE';
export const SET_RIDE_HISTORY = 'SET_RIDE_HISTORY';

// User Action Types
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_APP_LANGUAGE = 'SET_APP_LANGUAGE';

export const GET_PLANS_REQUEST = 'GET_PLANS_REQUEST';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAILURE = 'GET_PLANS_FAILURE';

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const CLEAR_BOOKING_DATA = 'CLEAR_BOOKING_DATA';

export const GET_SUB_SERVICES_REQUEST = 'GET_SUB_SERVICES_REQUEST';
export const GET_SUB_SERVICES_SUCCESS = 'GET_SUB_SERVICES_SUCCESS';
export const GET_SUB_SERVICES_FAILURE = 'GET_SUB_SERVICES_FAILURE';

// Self Sharing & Inter City Action Types
export const GET_AVAILABLE_TRIPS_REQUEST = 'GET_AVAILABLE_TRIPS_REQUEST';
export const GET_AVAILABLE_TRIPS_SUCCESS = 'GET_AVAILABLE_TRIPS_SUCCESS';
export const GET_AVAILABLE_TRIPS_FAILURE = 'GET_AVAILABLE_TRIPS_FAILURE';

export const CREATE_SELF_SHARING_BOOKING_REQUEST = 'CREATE_SELF_SHARING_BOOKING_REQUEST';
export const CREATE_SELF_SHARING_BOOKING_SUCCESS = 'CREATE_SELF_SHARING_BOOKING_SUCCESS';
export const CREATE_SELF_SHARING_BOOKING_FAILURE = 'CREATE_SELF_SHARING_BOOKING_FAILURE';

export const GET_SELF_SHARING_BOOKINGS_REQUEST = 'GET_SELF_SHARING_BOOKINGS_REQUEST';
export const GET_SELF_SHARING_BOOKINGS_SUCCESS = 'GET_SELF_SHARING_BOOKINGS_SUCCESS';
export const GET_SELF_SHARING_BOOKINGS_FAILURE = 'GET_SELF_SHARING_BOOKINGS_FAILURE';

export const CANCEL_SELF_SHARING_BOOKING_REQUEST = 'CANCEL_SELF_SHARING_BOOKING_REQUEST';
export const CANCEL_SELF_SHARING_BOOKING_SUCCESS = 'CANCEL_SELF_SHARING_BOOKING_SUCCESS';
export const CANCEL_SELF_SHARING_BOOKING_FAILURE = 'CANCEL_SELF_SHARING_BOOKING_FAILURE';

export const PAY_FULL_BALANCE_REQUEST = 'PAY_FULL_BALANCE_REQUEST';
export const PAY_FULL_BALANCE_SUCCESS = 'PAY_FULL_BALANCE_SUCCESS';
export const PAY_FULL_BALANCE_FAILURE = 'PAY_FULL_BALANCE_FAILURE';