const EndPoints = {
  authLogin: 'auth/login',
  signup: 'auth/signup',
  sendOtp: 'user/send-otp',
  verifyOtp: 'user/verify-otp',
  getPlans: 'user/getplan',
  createBooking: 'user/bookingrequest',
  createBookingParcel: 'parcel/booking/create',
  pagesByRole: 'pages/by-role',
  getInvoice: '/invoice',
  processPayment: 'user/processPayment',
  recharge: 'user/recharge',
  rechargeHistory: 'user/recharge-history',
  userWithdrawalHistory: 'user/withdrawal-history',
  userWithdrawalRequest: 'user/withdrawal-request',
  createOnSpotBooking: '/onspot/booking/create',
  userNotifications:'notifications/user',
  supportConversation: 'support/conversation',
  supportSend: 'support/send',
  appVersion: 'app-version',
};
export default EndPoints;